name: Actividad 1 - Hola Actions

# Permite ejecutar el workflow manualmente desde la pestaña Actions
on:
  workflow_dispatch:

jobs:
  informacion_estudiante:
    runs-on: ubuntu-latest

    steps:
      - name: Imprimir datos del estudiante
        run: |
          echo "Estudiante: [Tu Nombre y Apellido]"
          echo "Fecha actual: $(date +'%Y-%m-%d')"
          echo "Sistema Operativo del Runner: $RUNNER_OS"
